/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class canvas_InputCanvas */

#ifndef _Included_canvas_InputCanvas
#define _Included_canvas_InputCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef canvas_InputCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define canvas_InputCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef canvas_InputCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define canvas_InputCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef canvas_InputCanvas_FOCUS_TRAVERSABLE_SET
#define canvas_InputCanvas_FOCUS_TRAVERSABLE_SET 2L
#undef canvas_InputCanvas_TOP_ALIGNMENT
#define canvas_InputCanvas_TOP_ALIGNMENT 0.0f
#undef canvas_InputCanvas_CENTER_ALIGNMENT
#define canvas_InputCanvas_CENTER_ALIGNMENT 0.5f
#undef canvas_InputCanvas_BOTTOM_ALIGNMENT
#define canvas_InputCanvas_BOTTOM_ALIGNMENT 1.0f
#undef canvas_InputCanvas_LEFT_ALIGNMENT
#define canvas_InputCanvas_LEFT_ALIGNMENT 0.0f
#undef canvas_InputCanvas_RIGHT_ALIGNMENT
#define canvas_InputCanvas_RIGHT_ALIGNMENT 1.0f
#undef canvas_InputCanvas_serialVersionUID
#define canvas_InputCanvas_serialVersionUID -7644114512714619750LL
#undef canvas_InputCanvas_serialVersionUID
#define canvas_InputCanvas_serialVersionUID -2284879212465893870LL
/*
 * Class:     canvas_InputCanvas
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_canvas_InputCanvas_paint
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
