/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class control_Plotter */

#ifndef _Included_control_Plotter
#define _Included_control_Plotter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     control_Plotter
 * Method:    cleanList
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_control_Plotter_cleanList
  (JNIEnv *, jobject);

/*
 * Class:     control_Plotter
 * Method:    plot
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_control_Plotter_plot
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
