/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Numerics */

#ifndef _Included_main_Numerics
#define _Included_main_Numerics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_Numerics
 * Method:    initNumerics
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_Numerics_initNumerics
  (JNIEnv *, jclass);

/*
 * Class:     main_Numerics
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_Numerics_clean
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
