/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rpn_NativeCanvas */

#ifndef _Included_rpn_NativeCanvas
#define _Included_rpn_NativeCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef rpn_NativeCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define rpn_NativeCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef rpn_NativeCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define rpn_NativeCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef rpn_NativeCanvas_FOCUS_TRAVERSABLE_SET
#define rpn_NativeCanvas_FOCUS_TRAVERSABLE_SET 2L
#undef rpn_NativeCanvas_TOP_ALIGNMENT
#define rpn_NativeCanvas_TOP_ALIGNMENT 0.0f
#undef rpn_NativeCanvas_CENTER_ALIGNMENT
#define rpn_NativeCanvas_CENTER_ALIGNMENT 0.5f
#undef rpn_NativeCanvas_BOTTOM_ALIGNMENT
#define rpn_NativeCanvas_BOTTOM_ALIGNMENT 1.0f
#undef rpn_NativeCanvas_LEFT_ALIGNMENT
#define rpn_NativeCanvas_LEFT_ALIGNMENT 0.0f
#undef rpn_NativeCanvas_RIGHT_ALIGNMENT
#define rpn_NativeCanvas_RIGHT_ALIGNMENT 1.0f
#undef rpn_NativeCanvas_serialVersionUID
#define rpn_NativeCanvas_serialVersionUID -7644114512714619750LL
#undef rpn_NativeCanvas_serialVersionUID
#define rpn_NativeCanvas_serialVersionUID -2284879212465893870LL
/*
 * Class:     rpn_NativeCanvas
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_rpn_NativeCanvas_paint
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
